{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Skeaner",
    "module": "SkeanFrameWork",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.permissions-dispatcher",
          "module": "permissionsdispatcher",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-jackson",
          "version": {
            "requires": "2.6.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.6.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "com.github.franmontiel",
          "module": "PersistentCookieJar",
          "version": {
            "requires": "v1.0.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-support-v4",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-appcompat-v7",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-design",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-android",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-components",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-android-lifecycle",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-kotlin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-android-lifecycle-kotlin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.amap.api",
          "module": "map2d",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "com.amap.api",
          "module": "location",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "net.zetetic",
          "module": "android-database-sqlcipher",
          "version": {
            "requires": "4.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "android-database-sqlcipher",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "com.badoo.mobile",
          "module": "android-weak-handler",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-gif",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-video",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "it.sephiroth.android.library.imagezoom",
          "module": "imagezoom",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.davemorrissey.labs",
          "module": "subsampling-scale-image-view",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.github.Skeaner",
          "module": "Matisse",
          "version": {
            "requires": "0.5.3-beta3-extend-1.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "library"
            }
          ]
        },
        {
          "group": "com.blankj",
          "module": "utilcodex",
          "version": {
            "requires": "1.30.6"
          }
        },
        {
          "group": "in.srain.cube",
          "module": "ultra-ptr",
          "version": {
            "requires": "1.0.11"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "com.github.Skeaner",
          "module": "SublimePicker",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.Skeaner",
          "module": "EasyPermissionDialog",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.pgyer",
          "module": "analytics",
          "version": {
            "requires": "4.3.2"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "com.github.Skeaner",
          "module": "NumberProgressBar",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.chibatching.kotpref",
          "module": "kotpref",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.chibatching.kotpref",
          "module": "preference-screen-dsl",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.github.Skeaner.OldMaterialDialogs",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.Skeaner.OldMaterialDialogs",
          "module": "commons",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "input",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "bottomsheets",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-layout-kernel",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-header-classics",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-footer-classics",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-workmanager",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-navigation",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "com.hi-dhl",
          "module": "binding",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.github.DylanCaiCoding.ViewBindingKTX",
          "module": "viewbinding-ktx",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.github.DylanCaiCoding.ViewBindingKTX",
          "module": "viewbinding-brvah",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.github.mazenrashed",
          "module": "RecyclerView-FlexibleDivider",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.github.DylanCaiCoding",
          "module": "ActivityResultLauncher",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "SkeanFrameWork-2.3.1.aar",
          "url": "SkeanFrameWork-2.3.1.aar",
          "size": 744125,
          "sha512": "a175670341ca09074e53d017aadbec2ff42ff918525dbd4a56d0d95dbbbc3550ed458760a52a8b2b5deb3e1fe742392588432195082a4f7545fa763f951e660e",
          "sha256": "3befc114f915584744a21ca790b09249f901e25debdd56b47dd11713ce0a3d34",
          "sha1": "869006f7ded56ca4b433ad96a99eaffb64e5faac",
          "md5": "66765b6ffa4b1eefceaf63f82689f20c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.permissions-dispatcher",
          "module": "permissionsdispatcher",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-jackson",
          "version": {
            "requires": "2.6.4"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.6.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "com.github.franmontiel",
          "module": "PersistentCookieJar",
          "version": {
            "requires": "v1.0.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-support-v4",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-appcompat-v7",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-design",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-android",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-components",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-android-lifecycle",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-kotlin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-android-lifecycle-kotlin",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.amap.api",
          "module": "map2d",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "com.amap.api",
          "module": "location",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "net.zetetic",
          "module": "android-database-sqlcipher",
          "version": {
            "requires": "4.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "android-database-sqlcipher",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "com.badoo.mobile",
          "module": "android-weak-handler",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-gif",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-video",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "it.sephiroth.android.library.imagezoom",
          "module": "imagezoom",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.davemorrissey.labs",
          "module": "subsampling-scale-image-view",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.github.Skeaner",
          "module": "Matisse",
          "version": {
            "requires": "0.5.3-beta3-extend-1.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "library"
            }
          ]
        },
        {
          "group": "com.blankj",
          "module": "utilcodex",
          "version": {
            "requires": "1.30.6"
          }
        },
        {
          "group": "in.srain.cube",
          "module": "ultra-ptr",
          "version": {
            "requires": "1.0.11"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "com.github.Skeaner",
          "module": "SublimePicker",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.Skeaner",
          "module": "EasyPermissionDialog",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.pgyer",
          "module": "analytics",
          "version": {
            "requires": "4.3.2"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "com.github.Skeaner",
          "module": "NumberProgressBar",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.chibatching.kotpref",
          "module": "kotpref",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.chibatching.kotpref",
          "module": "preference-screen-dsl",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.github.Skeaner.OldMaterialDialogs",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.Skeaner.OldMaterialDialogs",
          "module": "commons",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "input",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "bottomsheets",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-layout-kernel",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-header-classics",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-footer-classics",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-workmanager",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-navigation",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "com.hi-dhl",
          "module": "binding",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.github.DylanCaiCoding.ViewBindingKTX",
          "module": "viewbinding-ktx",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.github.DylanCaiCoding.ViewBindingKTX",
          "module": "viewbinding-brvah",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.github.mazenrashed",
          "module": "RecyclerView-FlexibleDivider",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.github.DylanCaiCoding",
          "module": "ActivityResultLauncher",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "SkeanFrameWork-2.3.1.aar",
          "url": "SkeanFrameWork-2.3.1.aar",
          "size": 744125,
          "sha512": "a175670341ca09074e53d017aadbec2ff42ff918525dbd4a56d0d95dbbbc3550ed458760a52a8b2b5deb3e1fe742392588432195082a4f7545fa763f951e660e",
          "sha256": "3befc114f915584744a21ca790b09249f901e25debdd56b47dd11713ce0a3d34",
          "sha1": "869006f7ded56ca4b433ad96a99eaffb64e5faac",
          "md5": "66765b6ffa4b1eefceaf63f82689f20c"
        }
      ]
    }
  ]
}
